Make FeatureExtractor injectable
redis/redis-om-spring pull request #262
Opened 2023-06-12 10:31 UTC by Grogdunn

I want to make injectable FeatureExtractor because I don't need DJL. So everyone now can implement FeatureExtractor or use the provided DefaultFeatureExtractor.

Also removed `@Component` to avoid auto discovery (the bean is declared in configuration).

2023-06-13 16:28 UTC, bsbodden commented
Thank you @Grogdunn I agree this is a good idea; I tried to make it as unintrusive as possible but this is even better. I'll review soon.

2023-06-17 22:08 UTC, bsbodden commented on demos/roms-vss/src/main/resources/application.properties
I think you left some settings behind...

2023-06-17 22:09 UTC, bsbodden requested changes
Look good, if you can just remove the extra settings in the demo. Thanks!

2023-06-19 09:29 UTC, Grogdunn commented
removed my configuration ^^ sorry for that!

2023-06-20 23:53 UTC, bsbodden approved these changes
LGTM

2023-06-20 23:54 UTC, merged