#280 added the ability to save an enumeration as a number
redis/redis-om-spring pull request #335
Opened 2023-08-27 21:15 UTC by justTimTim

1. Added the ability to save enumerations not only as a string, but also as a number. you need to hang the annotation @Enumerated from package com.redis.om.spring.annotations
If necessary, I can change the title of the annotation
2. Slightly corrected the duplicated code

2023-08-29 16:10 UTC, bsbodden requested changes
This is great, if we can do without a new annotation even better. Let me know if that makes sense. If you can rebase and make those changes, and add a test I merge this for the 0.8.7 release. Thanks!

2023-08-29 16:10 UTC, bsbodden commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
@justTimTim I'm thinking that we can save ourselves the extra annotation an instead add an extra value to `SchemaFieldType` of either type `ENUM` OR `ORDINAL`? to force the use of the `EnumTypeAdapter` and create the right type of Index Schema Field?

2023-08-29 18:47 UTC, justTimTim commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
Hi! Got it, I'll do it today!

2023-08-29 20:08 UTC, justTimTim commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
Initially, I made the enumeration "EnumIndexType", but then I considered it superfluous and deleted it. 
In fact, I suggest in this case to make a separate enum  like "EnumIndexType", this will correspond to the principles of SOLID. 
it will be like 
public @interface Enumerated {
    EnumIndexType value() default EnumIndexType.ORDINAL;
}
But if you insist on adding two types to "SchemaFieldType" then no problem, I will add them. 
So what's your solution?))

2023-08-29 21:16 UTC, justTimTim commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
so, I missed one point, the enumeration is saved as a number only in case of indexing and therefore added the following code
     // enum without @indexed
     else if (field.isAnnotationPresent(Enumerated.class)) {
       Class<?> fieldType = ClassUtils.resolvePrimitiveIfNecessary(field.getType());
       gsonBuilder.registerTypeAdapter(fieldType, EnumTypeAdapter.of(fieldType));
     }

Perhaps in this case it makes no sense to add new fields to "SchemaFieldType"

2023-08-30 23:20 UTC, bsbodden commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
I think the additions to `SchemaFieldType` will suffice since we've already overload `@Indexed` to do things like resolved nested deep indexing. The overriding on the serialization based on indexing needs makes sense and we already kind of do it. So I'm good with that approach. Additionally, we could also add an extra enum field to `@Indexed` called `serialization` and use that to register indexing specific serializers (there are some tests for collection serializing where we do that manually with GSON annotations)

2023-08-30 23:21 UTC, bsbodden requested changes
See the comment inline

2023-08-31 18:03 UTC, justTimTim commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
@bsbodden  the fact is that we cannot remove @Enumerated, because this annotation first of all specifies in what format to save the enumeration, if it exists, then it will be saved as a number, even if there is no @Indexed annotation. If we remove the @Enumerated annotation and just add a field to the SchemaFieldType, then we can only store the enum as a number if that field is indexed. Accordingly, we leave this annotation and add a field to SchemaFieldType, and our indexing code will look like this:
    @Indexed(schemaFieldType = SchemaFieldType.ORDINAL)
    @Enumerated
   private SomeEnum type;
Am I understanding you correctly?

If we want to make it possible to save Enum as a number only when indexing, then @Enumerated can be removed.

2023-09-02 03:35 UTC, bsbodden commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
That's what I meant, the serialization modifications are in service of the indexing/searchability. So in this case I'm ok with having `@Indexed` dictate the format of the data in Redis. So like you said, make it save as an ordinal only when directed by the `@Indexed` annotation.

2023-09-02 04:09 UTC, bsbodden commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
To be clear... there might be a mechanism later on to add more control over the serialization even when not indexing a field but it'll likely be aligned with Spring Data's efforts in that direction.

2023-09-02 19:51 UTC, justTimTim commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
@bsbodden Understood. Corrected at your request. Most likely, in the future it will be difficult to fix it, keeping the inverse relationship, I'm talking about saving in number format without indexing the field

2023-09-02 22:55 UTC, bsbodden commented on redis-om-spring/src/main/java/com/redis/om/spring/RediSearchIndexer.java
I get it, it's that there is another request for that serialization flexibility which will be it's own API working on top of GSON and other "pluggable" JSON libraries/parser. So this feature right here it's only in the realm of indexing/searching where the needs of the "searchability" are the "boss".  I will review the rest of the PR today. Thanks for the contribution!

2023-09-04 04:31 UTC, bsbodden approved these changes
LGTM - I might make some changes before the release but this is great as is!

2023-09-04 04:33 UTC, merged